name: Build
on:
  push:
    branches:
      - stage # or the name of your main branch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

       # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |
              kubectl create namespace stage
              pwd
              kubectl apply -k . 
       # Check the sonarqube report here
      - name: Check the sonarqube report here
        run: | 
              SONAR_URL=`kubectl get svc sonarqube-sonarqube --output jsonpath='{.status.loadBalancer.ingress[0].ip}' -n sonarqube`
              echo "The SonarQube Reports are available at $SONAR_URL"

      # Wait for 60 seconds and get the preview of the applicaton 
      #- name: Wait for 60 seconds and get the preview of the applicaton
      #  run: | 
      #    sleep 60
      #    PRIVEW_URL=`kubectl get svc -n customer1-frontend-lb-myapp  --output jsonpath='{.status.loadBalancer.ingress[0].ip}' -n stage`
      #    echo "This is app preview URL $PRIVEW_URL" 
      # Delete stage namespace 
      #- name: Delete stage namespace
      #  run: | 
      #    sleep 60
      #    kubectl delete namespace stage          